master, pipeline hotfix

diff --git a/.github/workflows/trading_bot_ci.yml b/.github/workflows/trading_bot_ci.yml
--- a/.github/workflows/trading_bot_ci.yml
+++ b/.github/workflows/trading_bot_ci.yml
@@ -1,10 +1,8 @@
 name: trading_bot_ci.yml
 ## first pipeline version without docker images
 on:
-  push:
-    branches:
-      - master
-  pull_request:
+  push
+  pull_request
 
 jobs:
   stock_market_availability:
@@ -31,9 +29,13 @@ jobs:
           sudo apt-get install -y build-essential cmake python3 python3-dev python3-pip
       - name: Install boost from archive
         run: |
-          wget https://archives.boost.io/release/1.86.0/source/boost_1_86_0.tar.gz
+          sudo apt-get update
+          sudo apt-get install -y build-essential gcc g++ zlib1g-dev libbz2-dev python3-dev
+          wget https://boostorg.jfrog.io/artifactory/main/release/1.86.0/source/boost_1_86_0.tar.gz
           tar -xvzf boost_1_86_0.tar.gz
-          cd boost_1_86_0 && ./bootstrap.sh && ./b2 install  
+          cd boost_1_86_0
+          ./bootstrap.sh || { echo "Bootstrap failed"; cat bootstrap.log; exit 1; }
+          ./b2 install --prefix=~/boost || { echo "B2 install failed"; exit 1; }
 
       - name: Install Python dependencies
         run: |
