feature/add-pipeline, fixed pipeline exectution, removed redundant steps

diff --git a/.github/workflows/trading_bot_ci.yml b/.github/workflows/trading_bot_ci.yml
--- a/.github/workflows/trading_bot_ci.yml
+++ b/.github/workflows/trading_bot_ci.yml
@@ -1,41 +1,27 @@
 name: trading_bot_ci.yml
-on: [ push, pull_request ]
-jobs:
-  linters:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: Linters
-        run: # todo
 
+on:
+  push:
+    branches:
+      - main
+  pull_request:
+
+jobs:
   stock_market_availability:
     runs-on: ubuntu-22.04
     steps:
-      - name: stock market availability
-        run: # todo
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-  build_library_api:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: build library api
-        run: #todo
-
-  build_project:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: build project
-        run: #todo
-
-
-  build_docker:
-    runs-on: ubuntu-22.04
-    steps:
-      - name: build docker
-        run: #todo
-
+      - name: Check stock market availability
+        run: ./Scripts/availability_check.sh
 
   backtesting:
     runs-on: ubuntu-22.04
     steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
       - name: Install Python dependencies
         run: |
           python3 -m pip install --upgrade pip
@@ -44,10 +30,10 @@ jobs:
       - name: Extract data for backtesting
         run: |
           set -e
-          cd Backtesting
+          cd Backtesting/src
           for year in {2020..2024}
           do
-            if [ ! -f "Data_extracted/5m/BTCUSDT/${year}.csv" ]; then
+            if [ ! -f "data/Data_extracted/5m/BTCUSDT/${year}.csv" ]; then
               python3 binance_stats.py BTCUSDT 5m $year >> data_extraction.log 2>&1
               echo "Data for year $year extracted."
             else
@@ -62,34 +48,31 @@ jobs:
           cd Backtesting
           rm -rf build && mkdir build && cd build
           cmake ../
-          make || { echo "Build failed"; exit 1; }
+          make -j`nproc` || { echo "Build failed"; exit 1; }
           ./backtesting >> backtesting_results.log 2>&1
           echo "Backtesting completed."
 
       - name: Notify completion
         run: echo "Backtesting workflow completed successfully."
 
-  docker_image_tests:
+  autotest:
     runs-on: ubuntu-22.04
     steps:
-      - name: Install Dependencies
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Install dependencies
         run: sudo apt-get update && sudo apt-get install -y build-essential cmake
 
-      - name: Run Tests
+      - name: Build autotests
         run: |
-          set -e
-          cd Autotests
-          rm -rf build && mkdir build && cd build
-          cmake ../ || { echo "CMake configuration failed"; exit 1; }
-          make || { echo "Build failed"; exit 1; }
-          ./test_ > test_results.log 2>&1 || { echo "Tests failed"; exit 1; }
-          echo "Tests completed successfully."
+          cd Autotests && mkdir -p build && cd build
+          cmake ../
+          make -j`nproc`
 
-      - name: Upload Test Results (Optional)
-        if: always()
-        uses: actions/upload-artifact@v3
-        with:
-          name: test-results
-          path: Autotests/build/test_results.log
+      - name: Run autotests
+        run: |
+          ./test_ || { echo "Tests failed"; exit 1; }
 
-
+      - name: Notify completion
+        run: echo "Autotest workflow completed successfully."
